# Type Path Mode User Group Age Argument
d /run/systemd-sentry 0755 sentry sentry -
d /var/log/systemd-sentry 0750 sentry sentry -
d /var/lib/systemd-sentry 0750 sentry sentry -
d /var/log/systemd-sentry/incidents 0750 sentry sentry -
