//! Process crash and backtrace information from systemd-coredump.

use serde::{Deserialize, Serialize};

/// Extended attributes parsed from a coredump file.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct CoredumpXattrs {
    /// PID of crashed process.
    pub pid: Option<u32>,
    /// Signal number that terminated process.
    pub signal: Option<i32>,
    /// Command name.
    pub comm: Option<String>,
    /// Executable path.
    pub exe: Option<String>,
}

/// Crash event record parsed from journal or coredump storage.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CoredumpRecord {
    /// Target unit name that experienced the crash.
    pub unit: String,
    /// PID of the terminating process.
    pub pid: u32,
    /// Signal number (e.g. 11 for SIGSEGV, 6 for SIGABRT).
    pub signal: i32,
    /// Signal name string (e.g. "SIGSEGV", "SIGABRT").
    pub signal_name: String,
    /// Executable binary path (e.g. "/usr/bin/nginx").
    pub executable: Option<String>,
    /// Formatted stack trace generated by systemd-coredump.
    pub stack_trace: Option<String>,
    /// Path to external compressed core file if available.
    pub core_file: Option<String>,
    /// Timestamp of crash in microseconds.
    pub timestamp_usec: u64,
    /// User ID of process owner.
    pub uid: Option<u32>,
    /// Group ID of process owner.
    pub gid: Option<u32>,
}

impl CoredumpRecord {
    /// Constructs a basic crash record.
    pub fn new(unit: impl Into<String>, pid: u32, signal: i32, signal_name: impl Into<String>) -> Self {
        Self {
            unit: unit.into(),
            pid,
            signal,
            signal_name: signal_name.into(),
            executable: None,
            stack_trace: None,
            core_file: None,
            timestamp_usec: 0,
            uid: None,
            gid: None,
        }
    }

    /// Returns true if the terminating signal represents a memory safety violation.
    pub fn is_memory_fault(&self) -> bool {
        matches!(self.signal, 11 | 7 | 4)
    }
}
